name: wavy
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - matplotlib>=3.1
  - numpy>=1.15.4
  - scipy>=1.2.0
  - netCDF4
  - pyyaml
  - pyproj>=2.3
  - cartopy>=0.18.0
  - cmocean
  - joblib
  - scikit-learn>=0.19
  - pandas
  - pyGAM
  - scikit-sparse
