name: wavy
channels:
  - conda-forge
dependencies:
  - python<=3.12
  #- matplotlib>=3
  - matplotlib
  #- numpy>=1
  - numpy>
  #- scipy>=1
  - scipy
  - netCDF4
  - pyyaml
  #- pyproj>=3
  - pyproj
  #- cartopy>=0.21
  - cartopy
  - cmocean
  - joblib
  #- scikit-learn>=0.19
  - scikit-learn
  - pandas
  - pyGAM
  #- scikit-sparse==0.4.5
  - xarray
  - zarr
  - pyresample
  - dask
  - tqdm
  - pytest
  - pytest-benchmark
  - pylint
  - yapf
  - sphinx
  - python-dotenv
  - xdg
  #- sentinelsat
  - geojson
  - roaring-landmask
  - numba
  - trajan
  - pip
  #- pip:
  # - hidefix
