--- # specifications for collocation_class

path:
    platform:
        local: 
            nc: 
                path_template: ["/home/patrikb/tmp_collocation/%Y/%m/"]
                file_template: "varalias_model_vs_platform_sensor_coll_ts_\
                                ltleadtime_%Y%m.nc"
                strsub: ['varalias','model','platform','sensor','leadtime']
        remote:
    satellite_altimeter:
        local:
            nc:
                path_template:
                file_template: 
