--- # Additional information on variables 
# cf convention together with variable alias for wavy
# http://cfconventions.org/Data/cf-standard-names/69/build/cf-standard-name-table.html
# This config file sets the standard for how variables are handled 
# and treated within wavy as well as for the wavy putput files

#time
time:
    standard_name: time

# coordinates
lons: 
    standard_name: longitude
    units: degree_east
lats: 
    standard_name: latitude
    units: degree_north

# variables
Hs:
    standard_name: sea_surface_wave_significant_height
    units: m
    valid_range: [0., 30.]
Tp:
    standard_name: "sea_surface_wave_period_at_variance_spectral_\
                    density_maximum"
    units: s
    valid_range: [0., 30.]
Tm01:
    standard_name: "sea_surface_wave_mean_period_from_variance_spectral\
                    _density_first_frequency_moment"
    units: s
    valid_range: [0., 30.]
Tm02:
    standard_name: "sea_surface_wave_mean_period_from_variance_spectral\
                    _density_second_frequency_moment"
    units: s
    valid_range: [0., 30.]
Tm10:
    standard_name: "sea_surface_wave_mean_period_from_variance_spectral\
                    _density_inverse_frequency_moment"
    units: s
    valid_range: [0., 30.]
Pdir:
    standard_name: "sea_surface_wave_to_direction_at_variance_spectral\
                    _density_maximum"
    units: degree
    valid_range: [0.,360.]
    convention: oceanographic
Mdir:
    standard_name: sea_surface_wave_to_direction
    units: degree
    valid_range: [0.,360.]
    convention: oceanographic
ux:
    standard_name: x_wind
    alias: grid_eastward_wind
    units: m s-1
ua: 
    standard_name: eastward_wind
    units: m s-1
vy: 
    standard_name: y_wind 
    alias: grid_northward_wind
    units: m s-1
va: 
    standard_name: northward_wind
    units: m s-1
U: 
    standard_name: wind_speed
    units: m s-1
    aliases_of_vector_components: 
        alt1: [ua,va] 
        alt2: [ux,vy]
